server.port=${PORT:3000}
spring.application.name=user-api
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jackson.default-property-inclusion=non_null
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
