package com.baseball

// UI & Code Layout specific styling/DOM constants
object UiConstants {
    // HTML Tag Constants
    object Html {
        const val DIV = "div"
        const val SPAN = "span"
        const val BUTTON = "button"
        const val A = "a"
        const val P = "p"
        const val H1 = "h1"
        const val H2 = "h2"
        const val H3 = "h3"
        const val H4 = "h4"
        const val TABLE = "table"
        const val THEAD = "thead"
        const val TBODY = "tbody"
        const val TR = "tr"
        const val TH = "th"
        const val TD = "td"
        const val SELECT = "select"
        const val OPTION = "option"
        const val INPUT = "input"
        const val LABEL = "label"
        const val HEADER = "header"
        const val NAV = "nav"
        const val MAIN = "main"
        const val FORM = "form"
        const val STRONG = "strong"
        const val HR = "hr"
        const val TEXTAREA = "textarea"
    }

    // CSS Property Name Constants
    object Css {
        const val DISPLAY = "display"
        const val HEIGHT = "height"
        const val WIDTH = "width"
        const val POSITION = "position"
        const val TOP = "top"
        const val LEFT = "left"
        const val BOTTOM = "bottom"
        const val RIGHT = "right"
        const val MARGIN = "margin"
        const val MARGIN_TOP = "margin-top"
        const val MARGIN_BOTTOM = "margin-bottom"
        const val MARGIN_LEFT = "margin-left"
        const val MARGIN_RIGHT = "margin-right"
        const val PADDING = "padding"
        const val PADDING_LEFT = "padding-left"
        const val PADDING_RIGHT = "padding-right"
        const val PADDING_TOP = "padding-top"
        const val PADDING_BOTTOM = "padding-bottom"
        const val COLOR = "color"
        const val BACKGROUND = "background"
        const val BACKGROUND_COLOR = "background-color"
        const val BORDER = "border"
        const val BORDER_TOP = "border-top"
        const val BORDER_BOTTOM = "border-bottom"
        const val BORDER_LEFT = "border-left"
        const val BORDER_RIGHT = "border-right"
        const val BORDER_RADIUS = "border-radius"
        const val BORDER_COLLAPSE = "border-collapse"
        const val FONT_WEIGHT = "font-weight"
        const val FONT_SIZE = "font-size"
        const val TEXT_ALIGN = "text-align"
        const val TEXT_DECORATION = "text-decoration"
        const val CURSOR = "cursor"
        const val Z_INDEX = "z-index"
        const val TRANSFORM = "transform"
        const val OPACITY = "opacity"
        const val GAP = "gap"
        const val FLEX = "flex"
        const val FLEX_DIRECTION = "flex-direction"
        const val JUSTIFY_CONTENT = "justify-content"
        const val ALIGN_ITEMS = "align-items"
        const val OVERFLOW = "overflow"
        const val OVERFLOW_X = "overflow-x"
        const val OVERFLOW_Y = "overflow-y"
        const val MAX_WIDTH = "max-width"
        const val MAX_HEIGHT = "max-height"
        const val MIN_HEIGHT = "min-height"
        const val BOX_SIZING = "box-sizing"
        const val POINTER_EVENTS = "pointer-events"
        const val WHITE_SPACE = "white-space"
        const val BACKDROP_FILTER = "backdrop-filter"
        const val TRANSITION = "transition"
        const val BOX_SHADOW = "box-shadow"
        const val LINE_HEIGHT = "line-height"
    }

    // CSS Standard Value Constants
    object CssValues {
        const val NONE = "none"
        const val BLOCK = "block"
        const val INLINE_BLOCK = "inline-block"
        const val FLEX = "flex"
        const val CENTER = "center"
        const val LEFT = "left"
        const val RIGHT = "right"
        const val ABSOLUTE = "absolute"
        const val RELATIVE = "relative"
        const val BOLD = "bold"
        const val NORMAL = "normal"
        const val POINTER = "pointer"
        const val COLUMN = "column"
        const val ROW = "row"
        const val NOWRAP = "nowrap"
        const val HIDDEN = "hidden"
        const val AUTO = "auto"
        const val BORDER_BOX = "border-box"
        const val COLLAPSE = "collapse"
        const val MIDDLE = "middle"
        const val UNDERLINE = "underline"
        const val LINE_THROUGH = "line-through"
        const val FLEX_END = "flex-end"
        const val SPACE_BETWEEN = "space-between"
    }

    // CSS Class Names
    object Classes {
        const val BTN = "btn"
        const val BTN_PRIMARY = "btn-primary"
        const val BTN_SECONDARY = "btn-secondary"
        const val BTN_DANGER = "btn-danger"
        const val BTN_ACTION = "btn-action"
        const val CARD = "card"
        const val FORM_CONTROL = "form-control"
        const val TAB_HEADERS = "tab-headers"
        const val TAB_HEADER = "tab-header"
        const val TAB_CONTAINER = "tab-container"
        const val TABLE_CONTAINER = "table-container"
    }
}
