package fitnessapi.domain

private val ALIASES = mapOf(
    "body_mass" to "body_mass",
    "weight" to "body_mass",
    "bodymass" to "body_mass",
    "height" to "height",
    "neck" to "neck",
    "waist" to "waist",
    "hip" to "hip",
    "hips" to "hip",
    "chest" to "chest",
    "upper_arm" to "upper_arm",
    "arm" to "upper_arm",
    "bicep" to "upper_arm",
    "thigh" to "thigh",
    "calf" to "calf",
    "heart_rate" to "heart_rate",
    "heartrate" to "heart_rate",
    "hr" to "heart_rate",
    "resting_heart_rate" to "resting_heart_rate",
    "rhr" to "resting_heart_rate",
    "hrv_rmssd" to "hrv_rmssd",
    "hrv" to "hrv_rmssd",
    "steps" to "steps",
    "distance" to "distance",
    "dist" to "distance",
    "sleep" to "sleep",
    "energy" to "energy_total",
    "energy_total" to "energy_total",
    "energy_active" to "energy_active",
    "calories" to "energy_total",
    "kcal" to "energy_total",
    "oxygen_sat" to "oxygen_sat",
    "spo2" to "oxygen_sat",
    "bmr" to "bmr",
    "speed" to "speed",
    "floors" to "floors",
    "exercise" to "exercise",
    "body_fat" to "body_fat",
    "bodyfat" to "body_fat",
    "bf" to "body_fat",
    "lean_mass" to "lean_mass",
    "vo2max" to "vo2max",
    "sit_and_reach" to "sit_and_reach",
    "knee_to_wall" to "knee_to_wall",
    "active_knee_extension" to "active_knee_extension",
    "shoulder_flexion" to "shoulder_flexion",
    "shoulder_er" to "shoulder_er",
    "hip_ir" to "hip_ir",
    "hip_er" to "hip_er",
    "wrist_extension" to "wrist_extension",
)

fun parseMetricId(raw: String): String? {
    val key = raw.trim().lowercase().replace(Regex("[\\s-]+"), "_")
    return ALIASES[key]
}
