#!/usr/bin/env python3
"""Write the Grafana dashboards to disk, or check the committed copies match.

The dashboards are provisioned at boot from deploy/grafana/provisioning/dashboards,
so a rebuild comes back with them rather than depending on one session in the UI.
They are generated rather than hand-written because Grafana's JSON is deeply
nested and easy to get subtly wrong. The board contents live in
grafana_dashboards.py and the panel shapes in grafana_panels.py; this is the
writer.

--check is the guard that matters: it fails when a hand-edit to a generated file
has drifted from the generator, which would otherwise be silently reverted by the
next regeneration.

Run: python tools/build_grafana_dashboards.py [--check]
Env:  none.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from grafana_dashboards import auth, errors, overview, services

OUT = (
    Path(__file__).resolve().parent.parent
    / "deploy"
    / "grafana"
    / "provisioning"
    / "dashboards"
)


DASHBOARDS = {
    "fleet-overview.json": overview,
    "errors.json": errors,
    "auth.json": auth,
    "services.json": services,
}


PROVIDER_YAML = """
# Grafana loads the dashboards in this directory at boot, so they return
# after a rebuild instead of depending on one session in the UI. The JSON
# files are generated by tools/build_grafana_dashboards.py -- edit that.
apiVersion: 1

providers:
    - name: webapp-workbench
      orgId: 1
      folder: Logs
      folderUid: logs
      type: file
      disableDeletion: true
      # Let a dashboard edited in the UI survive a restart until the next
      # rebuild regenerates the file.
      allowUiUpdates: true
      updateIntervalSeconds: 30
      options:
        path: /etc/grafana/provisioning/dashboards
        foldersFromFilesStructure: false
"""


def write_lf(path: Path, text: str) -> None:
    """Write with LF endings regardless of host.

    Path.write_text translates newlines to the platform default, so generating
    these on Windows produced CRLF in files that are then baked into a Linux
    image. Grafana tolerates it, but this repo's yamllint gate does not, and a
    file whose line endings depend on the machine that produced it is not
    reproducible.
    """
    path.write_bytes(text.encode("utf-8"))


def main() -> int:
    if "--check" in sys.argv:
        bad = 0
        for name, build in DASHBOARDS.items():
            path = OUT / name
            if not path.exists():
                print(f"  MISSING {name}")
                bad += 1
                continue
            want = json.dumps(build(), indent=2, sort_keys=True) + "\n"
            got = path.read_text()
            same = json.loads(got) == json.loads(want)
            print(f"  {'ok  ' if same else 'DIFF'} {name}")
            bad += 0 if same else 1
        print(f"{len(DASHBOARDS) - bad}/{len(DASHBOARDS)} dashboards current")
        return 1 if bad else 0

    OUT.mkdir(parents=True, exist_ok=True)
    for name, build in DASHBOARDS.items():
        write_lf(OUT / name, json.dumps(build(), indent=2, sort_keys=True))
        print(f"  wrote {name}")
    write_lf(OUT / "dashboards.yaml", PROVIDER_YAML)
    print("  wrote dashboards.yaml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
